name: calc
description: it do calculation
publish_to: 'none' 
version: 1.0.0+1

msix_config:
  display_name: Matematik Calculator
  publisher_display_name: Fahmi Hidayat
  identity_name: Fahmih.calculator
  msix_version: 1.0.0.0
  logo_path: assets/app_icon.png
  capabilities: internetClient

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  flutter_acrylic: ^1.1.2
  device_info_plus: ^8.2.0
  google_fonts: ^4.0.3
  fluentui_system_icons: ^1.1.199
  get: ^4.6.5
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  go_router: ^6.5.8
  ffi: ^2.0.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.11.0
  


flutter:
  uses-material-design: true
  assets:
  - assets/app_icon.png






